// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drjalxnoidqzehbehtin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyamFseG5vaWRxemVoYmVodGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjA3MDQsImV4cCI6MjA2MjY5NjcwNH0.R_wMZa8qpQ6i7S3dOZDHmeKaOopXH-2zPcJNhnHXa_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);